version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: dragonfit-db
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    container_name: dragonfit-api
    restart: always
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=MONGO_URL
      - DB_NAME=dragonfit
      - JWT_SECRET=${JWT_SECRET:-2f5f3a7abb14b2854ee447cdfbc04292a4c7ea70a7d2aaf2fa3f96597a1b5226}
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: dragonfit-web
    restart: always
    ports:
      - "3000:80"
    environment:
      - REACT_APP_BACKEND_URL=${BACKEND_URL:-https://dragon-fit.vercel.app}
    depends_on:
      - backend

volumes:
  mongodb_data:
